// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Feature: typeof import('./components/block/Feature.vue')['default']
    Footer: typeof import('./components/global/Footer.vue')['default']
    Header: typeof import('./components/global/Header.vue')['default']
    Hero: typeof import('./components/block/Hero.vue')['default']
    Info: typeof import('./components/block/Info.vue')['default']
    Location: typeof import('./components/block/Location.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Service: typeof import('./components/block/Service.vue')['default']
  }
}
